# Generated by Django 4.1.8 on 2023-04-24 13:23

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", phone_field.models.PhoneField(max_length=31)),
                ("number_of_guests", models.PositiveIntegerField()),
                ("date", models.DateField()),
                ("time", models.SmallIntegerField()),
                (
                    "occasion",
                    models.CharField(
                        choices=[
                            ("Birthday", "Birthday"),
                            ("Wedding", "Wedding"),
                            ("Reunion", "Reunion"),
                            ("Date", "Date"),
                            ("Others", "Others"),
                        ],
                        default="Birthday",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("cover_image", models.ImageField(upload_to="littleLemon/menu/")),
                ("description", models.TextField(max_length=1000)),
                (
                    "price",
                    models.DecimalField(db_index=True, decimal_places=2, max_digits=6),
                ),
                ("featured", models.BooleanField(db_index=True, default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="restaurant.category",
                    ),
                ),
            ],
        ),
    ]
